### ISSUE TITLE
Please specify the LICENSE for this code

### ISSUE THREAD

**Issue by silverweed** [sprain/PHP-MySQL-Session-Handler#6]
I'd like to use your class in my project, but you haven't specified a proper license for your work, which means it automatically gets copyrighted and no one can use it without your explicit permission.

If your intent is to make this class usable, please insert a license, either as a LICENSE file in this repo, or in the header comment of your main class, so other people may use it as they wish.

(Good examples of free software licenses are GPL, MIT, BSD, Apache License, WTFPL, MPL)

**Comment by sprain** [comment]
Go ahead and use it. This is your permission.
